---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/camel.svg"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "testmetrics"
    version: "0.0.1-SNAPSHOT"
    group: "avianca.com.co"
  name: "testmetrics"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "testmetrics"
    provider: "fabric8"
    group: "avianca.com.co"
